modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="test"
version="1.0.0"
displayName="test"
credits="idk"
authors="Sonmogaji"
logoFile="logo.png" #optional

[[dependencies.test]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"






